spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polisee
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  kakao:
    client-id: bd6499622dab0cd962a9b5c05eba5135
    redirect-uri: http://localhost:8080/auth/login/code/kakao
    scope: profile_nickname
    authorization-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

jwt:
  secret: 3R2dp8G4F8Pbx2SyxB5K1Vyz5DZnB9YZdpZFeTFffS8?








